### ISSUE TITLE
High Speed MTU modification of a deployed DPF cluster is not supported

### ISSUE THREAD

**Issue by itailev** [NVIDIA/doca-platform#15]
It is possible to deploy DPF cluster with a custom MTU value, however once deployed it is not possible to modify the MTU value which is applied on multiple distributed components.

### Workaround:
Uninstall DPF and re-install from scratch using the new MTU value.

An example of DPFOperatorConfig with custom MTU:
```
 apiVersion: operator.dpu.nvidia.com/v1alpha1
 kind: DPFOperatorConfig
 metadata:
   name: dpfoperatorconfig
   namespace: dpf-operator-system
 spec:
   networking:
     highSpeedMTU: 9000
```
